import { Inter } from 'next/font/google'
import '../styles/main.scss'
import { title } from 'process'
import { Html } from 'next/document'

const Inter = Inter({ subset: ['latin'] })

export const metadata = {
    title: 'create Next App',
    description: 'generated by next app',
}
eport default function Rootlayout({ children }) {
    return (
        <html lang="en">
            <body className={internal.className}>{children}</body>
        </html>
    )
}